POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Nestjs good for enterprice applications",
  "postType": "post",
  "slug": "builiding-enterprise-applications",
  "status": "draft",
  "content": "Nestjs is a robust language, with modules, seervices and controllers. It's good for enterprise applications",
  "schema": "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\"},\"age\":{\"type\":\"number\"}}}",
  "featuredImageUrl": "https://example.com/nestjs-6.jpg",
  "publishOn": "2026-05-18T12:00:00",
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\":true}"
  }
}